version: '3.8'

services:
  mail-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yandex-mail-telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"